name: doc

on:
  push:
    branches: [ doc ]

  workflow_dispatch:

jobs:
  doc:
    name: Publish doc
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-versions: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - uses: StoneMoe/setup-antlr4@v1.0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build Lexer
        run: >-
          antlr -Dlanguage=Python3 mongoengine_dsl/lexer/MongoEngineDSL.g4

      - name: Build docs
        run: |
          poetry install -E doc
          poetry run mkdocs build

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
